from typing import Protocol, List, Optional
from runtime.api.schemas.tasks import ExecutionTask, ExecutionReport

class SandboxInterface(Protocol):
    """
    Interface for isolated execution environments.
    """
    async def bootstrap(self, config: Optional[dict] = None) -> bool: ...
    async def execute_command(self, command: str, operation_type: str = "command_execution_default") -> dict: ...
    async def upload_file(self, source: str, destination: str) -> bool: ...
    async def download_file(self, source: str, destination: str) -> bool: ...
    async def create_snapshot(self) -> str: ...
    async def restore_snapshot(self, snapshot_id: str) -> bool: ...
    async def cleanup(self) -> bool: ...

class ValidatorInterface(Protocol):
    """
    Interface for execution-grounded validation.
    """
    async def validate(self, task: ExecutionTask, sandbox: SandboxInterface) -> bool: ...
    async def get_diagnostics(self) -> List[str]: ...

class RepairInterface(Protocol):
    """
    Interface for autonomous repair strategies.
    """
    async def repair(self, failure_context: dict, sandbox: SandboxInterface) -> bool: ...

class OrchestratorInterface(Protocol):
    """
    The central coordinator for the execution lifecycle.
    """
    async def run_task(self, task: ExecutionTask) -> ExecutionReport: ...
    async def stop_task(self, task_id: str) -> bool: ...
    async def get_status(self, task_id: str) -> str: ...
