from fastapi import FastAPI
import uvicorn

app = FastAPI(title="Generated API")

@app.get("/")
async def root():
    return {"status": "online", "message": "Generated by Antigravity Runtime"}

@app.get("/health")
async def health():
    return {"status": "healthy"}

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)






